name: "blog.mars3142.de"
description: "Blog of mars3142."

url: "http://blog.mars3142.org"

#paginate: 5
#paginate_path: "page:num"

markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md

#permalink: pretty
highlighter: pygments

exclude: ['CNAME', 'README.md']

#safe: true
lsi: false

github:
    project_title: "blog"
    project_tagline: "Blog of mars3142"

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap