on:
  schedule:
    - cron: "0 7 * * 1,4"
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:
    # to run manual builds

jobs:
  build_and_deploy_hugo_site:
    runs-on: ubuntu-latest
    name: Build and deploy Hugo site

    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.147.7"

      - name: Checkout repo on source branch
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build site and push to release branch
        uses: aormsby/hugo-deploy-to-pages@v2
        id: build_step # <<for outputs>>
        with:
          source_branch: "main"
          release_branch: "gh-pages"
          full_rebuild: true
          # submodule_release_branch: 'subbed' <<only provide if you are publishing to directory with git submodule>>
          # hugo_publish_directory: 'documents'   <<publish to another directory if needed>>
          # hugo_build_options: '-D --minify --ignoreCache' <<hugo build cis customizable>>
          # commit_message: "I love this action."
          # test_mode: true <<enable to run a few verification tests before your first live run>>

          # <<lots of other options!>>
